### ISSUE TITLE
Trying to run the library but failed.

### ISSUE THREAD

**Issue by hyunoosung** [rheesh/react-native-image-kit#1]
This repo. has a few issues when I tried.
Got conflict with default expo init project.
The lib only take static file. I would like to use this with photo taken form camera or from device's library.

**Comment by rheesh** [comment]
Thank you for your comments.
Can you upload some information on error messages, etc?
Both the photo library and the camera should be available, as noted in the readme.md. (Camera function has been updated today.)
You can see the working sample code at : [https://github.com/rheesh/Emarks](https://github.com/rheesh/Emarks)

**Comment by hyunoosung** [comment]
wow I just ran your sample and really amazed!!!
this repo. should get a lot of attention as there are no other options for expo projects.
Thumbs up for your hard work!
And please guide me to donate beside google play store as I don't own google play store account.
